In [ ]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline

In [ ]:
!wget https://archive.ics.uci.edu/ml/machine-learning-databases/00501/PRSA2017_Data_20130301-20170228.zip
!unzip PRSA2017_Data_20130301-20170228.zip

--2023-03-21 16:30:33--  https://archive.ics.uci.edu/ml/machine-learning-databases/00501/PRSA2017_Data_20130301-20170228.zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7959991 (7.6M) [application/x-httpd-php]
Saving to: ‘PRSA2017_Data_20130301-20170228.zip’

PRSA2017_Data_20130 100%[===================>]   7.59M  11.9MB/s    in 0.6s

2023-03-21 16:30:34 (11.9 MB/s) - ‘PRSA2017_Data_20130301-20170228.zip’ saved [7959991/7959991]

Archive:  PRSA2017_Data_20130301-20170228.zip
   creating: PRSA_Data_20130301-20170228/
  inflating: PRSA_Data_20130301-20170228/PRSA_Data_Aotizhongxin_20130301-20170228.csv
  inflating: PRSA_Data_20130301-20170228/PRSA_Data_Changping_20130301-20170228.csv
  inflating: PRSA_Data_20130301-20170228/PRSA_Data_Dingling_20130301-20170228.csv
  inflating: PRSA_Data_20130301-20170228/PRSA_Data_Dongsi_20130301-20170228.csv
  inflating: PRSA_Data_20130301-20170228/PRSA_Data_Guanyuan_20130301-20170228.csv
  inflating: PRSA_Data_20130301-20170228/PRSA_Data_Gucheng_20130301-20170228.csv
  inflating: PRSA_Data_20130301-20170228/PRSA_Data_Huairou_20130301-20170228.csv
  inflating: PRSA_Data_20130301-20170228/PRSA_Data_Nongzhanguan_20130301-20170228.csv
  inflating: PRSA_Data_20130301-20170228/PRSA_Data_Shunyi_20130301-20170228.csv
  inflating: PRSA_Data_20130301-20170228/PRSA_Data_Tiantan_20130301-20170228.csv
  inflating: PRSA_Data_20130301-20170228/PRSA_Data_Wanliu_20130301-20170228.csv
  inflating: PRSA_Data_20130301-20170228/PRSA_Data_Wanshouxigong_20130301-20170228.csv

In [ ]:
!head PRSA_Data_20130301-20170228/PRSA_Data_Aotizhongxin_20130301-20170228.csv

"No","year","month","day","hour","PM2.5","PM10","SO2","NO2","CO","O3","TEMP","PRES","DEWP","RAIN","wd","WSPM","station"
1,2013,3,1,0,4,4,4,7,300,77,-0.7,1023,-18.8,0,"NNW",4.4,"Aotizhongxin"
2,2013,3,1,1,8,8,4,7,300,77,-1.1,1023.2,-18.2,0,"N",4.7,"Aotizhongxin"
3,2013,3,1,2,7,7,5,10,300,73,-1.1,1023.5,-18.2,0,"NNW",5.6,"Aotizhongxin"
4,2013,3,1,3,6,6,11,11,300,72,-1.4,1024.5,-19.4,0,"NW",3.1,"Aotizhongxin"
5,2013,3,1,4,3,3,12,12,300,72,-2,1025.2,-19.5,0,"N",2,"Aotizhongxin"
6,2013,3,1,5,5,5,18,18,400,66,-2.2,1025.6,-19.6,0,"N",3.7,"Aotizhongxin"
7,2013,3,1,6,3,3,18,32,500,50,-2.6,1026.5,-19.1,0,"NNE",2.5,"Aotizhongxin"
8,2013,3,1,7,3,6,19,41,500,43,-1.6,1027.4,-19.1,0,"NNW",3.8,"Aotizhongxin"
9,2013,3,1,8,3,6,16,43,500,45,0.1,1028.3,-19.2,0,"NNW",4.1,"Aotizhongxin"

In [ ]:
df = pd.read_csv("PRSA_Data_20130301-20170228/PRSA_Data_Aotizhongxin_20130301-20170228.csv")
df.head()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station
0,1,2013,3,1,0,4.0,4.0,4.0,7.0,300.0,77.0,-0.7,1023.0,-18.8,0.0,NNW,4.4,Aotizhongxin
1,2,2013,3,1,1,8.0,8.0,4.0,7.0,300.0,77.0,-1.1,1023.2,-18.2,0.0,N,4.7,Aotizhongxin
2,3,2013,3,1,2,7.0,7.0,5.0,10.0,300.0,73.0,-1.1,1023.5,-18.2,0.0,NNW,5.6,Aotizhongxin
3,4,2013,3,1,3,6.0,6.0,11.0,11.0,300.0,72.0,-1.4,1024.5,-19.4,0.0,NW,3.1,Aotizhongxin
4,5,2013,3,1,4,3.0,3.0,12.0,12.0,300.0,72.0,-2.0,1025.2,-19.5,0.0,N,2.0,Aotizhongxin

In [ ]:
df.isnull().sum()

PM2.5    0
PM10     0
SO2      0
NO2      0
CO       0
O3       0
TEMP     0
PRES     0
DEWP     0
RAIN     0
WSPM     0
date     0
dtype: int64

In [ ]:
df['date'] = pd.to_datetime(dict(year=df.year, month=df.month, day=df.day))
df.head()

,No,year,month,day,hour,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,station,date
0,1,2013,3,1,0,4.0,4.0,4.0,7.0,300.0,77.0,-0.7,1023.0,-18.8,0.0,NNW,4.4,Aotizhongxin,2013-03-01
1,2,2013,3,1,1,8.0,8.0,4.0,7.0,300.0,77.0,-1.1,1023.2,-18.2,0.0,N,4.7,Aotizhongxin,2013-03-01
2,3,2013,3,1,2,7.0,7.0,5.0,10.0,300.0,73.0,-1.1,1023.5,-18.2,0.0,NNW,5.6,Aotizhongxin,2013-03-01
3,4,2013,3,1,3,6.0,6.0,11.0,11.0,300.0,72.0,-1.4,1024.5,-19.4,0.0,NW,3.1,Aotizhongxin,2013-03-01
4,5,2013,3,1,4,3.0,3.0,12.0,12.0,300.0,72.0,-2.0,1025.2,-19.5,0.0,N,2.0,Aotizhongxin,2013-03-01

In [ ]:
df.drop(['date'], axis=1,inplace=True)
df.head()

   index  PM2.5  PM10   SO2   NO2     CO    O3  TEMP    PRES  DEWP  RAIN  WSPM
0      0    4.0   4.0   4.0   7.0  300.0  77.0  -0.7  1023.0 -18.8   0.0   4.4
1      1    8.0   8.0   4.0   7.0  300.0  77.0  -1.1  1023.2 -18.2   0.0   4.7
2      2    7.0   7.0   5.0  10.0  300.0  73.0  -1.1  1023.5 -18.2   0.0   5.6
3      3    6.0   6.0  11.0  11.0  300.0  72.0  -1.4  1024.5 -19.4   0.0   3.1
4      4    3.0   3.0  12.0  12.0  300.0  72.0  -2.0  1025.2 -19.5   0.0   2.0

In [ ]:
#df.set_index('date')
df.head()

,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,wd,WSPM,date
0,4.0,4.0,4.0,7.0,300.0,77.0,-0.7,1023.0,-18.8,0.0,NNW,4.4,2013-03-01
1,8.0,8.0,4.0,7.0,300.0,77.0,-1.1,1023.2,-18.2,0.0,N,4.7,2013-03-01
2,7.0,7.0,5.0,10.0,300.0,73.0,-1.1,1023.5,-18.2,0.0,NNW,5.6,2013-03-01
3,6.0,6.0,11.0,11.0,300.0,72.0,-1.4,1024.5,-19.4,0.0,NW,3.1,2013-03-01
4,3.0,3.0,12.0,12.0,300.0,72.0,-2.0,1025.2,-19.5,0.0,N,2.0,2013-03-01

In [ ]:
df.isnull().sum()

PM2.5    0
PM10     0
SO2      0
NO2      0
CO       0
O3       0
TEMP     0
PRES     0
DEWP     0
RAIN     0
WSPM     0
date     0
dtype: int64

In [ ]:
df['PM2.5'].fillna(value=df['PM2.5'].mean(), inplace=True)
df['PM10'].fillna(value=df['PM10'].mean(), inplace=True)
df['SO2'].fillna(value=df['SO2'].mean(), inplace=True)
df['NO2'].fillna(value=df['NO2'].mean(), inplace=True)
df['CO'].fillna(value=df['CO'].mean(), inplace=True)
df['O3'].fillna(value=df['O3'].mean(), inplace=True)
df['TEMP'].fillna(value=df['TEMP'].mean(), inplace=True)
df['PRES'].fillna(value=df['PRES'].mean(), inplace=True)
df['DEWP'].fillna(value=df['DEWP'].mean(), inplace=True)
df['RAIN'].fillna(value=df['RAIN'].mean(), inplace=True)
df['WSPM'].fillna(value=df['WSPM'].mean(), inplace=True)

In [ ]:
df.head()

,PM2.5,PM10,SO2,NO2,CO,O3,TEMP,PRES,DEWP,RAIN,WSPM,date
0,4.0,4.0,4.0,7.0,300.0,77.0,-0.7,1023.0,-18.8,0.0,4.4,2013-03-01
1,8.0,8.0,4.0,7.0,300.0,77.0,-1.1,1023.2,-18.2,0.0,4.7,2013-03-01
2,7.0,7.0,5.0,10.0,300.0,73.0,-1.1,1023.5,-18.2,0.0,5.6,2013-03-01
3,6.0,6.0,11.0,11.0,300.0,72.0,-1.4,1024.5,-19.4,0.0,3.1,2013-03-01
4,3.0,3.0,12.0,12.0,300.0,72.0,-2.0,1025.2,-19.5,0.0,2.0,2013-03-01

In [ ]:
df=df.reset_index()

df=pd.melt(df, id_vars='index', value_vars=['PM2.5',	'PM10',	'SO2',	'NO2',	'CO',	'O3',	'TEMP',	'PRES',	'DEWP',	'RAIN',	'WSPM'])
df.columns=['ds','weeks','y']
df.head()

                             ds  weeks    y
0 1970-01-01 00:00:00.000000000  PM2.5  4.0
1 1970-01-01 00:00:00.000000001  PM2.5  8.0
2 1970-01-01 00:00:00.000000002  PM2.5  7.0
3 1970-01-01 00:00:00.000000003  PM2.5  6.0
4 1970-01-01 00:00:00.000000004  PM2.5  3.0

In [ ]:
#df=df.reset_index()
#df['index']=df['index'].astype('datetime64[ns]')
df.head()
#ts_code = df['date'].astype('category').cat.codes.values
#ts_code

                             ds  weeks    y
0 1970-01-01 00:00:00.000000000  PM2.5  4.0
1 1970-01-01 00:00:00.000000001  PM2.5  8.0
2 1970-01-01 00:00:00.000000002  PM2.5  7.0
3 1970-01-01 00:00:00.000000003  PM2.5  6.0
4 1970-01-01 00:00:00.000000004  PM2.5  3.0

In [ ]:
groups_by_ticker=df.groupby('weeks')
groups_by_ticker.groups.keys()

dict_keys(['CO', 'DEWP', 'NO2', 'O3', 'PM10', 'PM2.5', 'PRES', 'RAIN', 'SO2', 'TEMP', 'WSPM'])

In [ ]:
from prophet import Prophet

In [ ]:
def train_and_forecast (group1):
  m= Prophet()
  m.fit(group1)
  future1 = m.make_future_dataframe(periods=0)
  forecast1 = m.predict(future1)[['ds', 'yhat', 'yhat_lower', 'yhat_upper']]
  forecast1['weeks'] = group1['weeks'].iloc[0]
  return forecast1[['ds', 'weeks', 'yhat','yhat_lower', 'yhat_upper']]

In [ ]:
ticker_list = ['PM2.5',	'PM10',	'SO2',	'NO2',	'CO',	'O3',	'TEMP',	'PRES',	'DEWP',	'RAIN',	'WSPM']
for_loop_forecast1=pd.DataFrame()

for weeks in ticker_list:
  # Get the data for the ticker
  group1 = groups_by_ticker.get_group(weeks)  
  # Make forecast
  forecast1 = train_and_forecast(group1)
  # Add the forecast results to the dataframe
  for_loop_forecast1 = pd.concat((for_loop_forecast1, forecast1))

INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/napegg5q.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/jlu_e4u3.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.9/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=91515', 'data', 'file=/tmp/tmp0lbuvohe/napegg5q.json', 'init=/tmp/tmp0lbuvohe/jlu_e4u3.json', 'output', 'file=/tmp/tmp0lbuvohe/prophet_model7tsbmgc0/prophet_model-20230321173426.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
17:34:26 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing

KeyboardInterrupt: ignored

In [ ]:
ticker_list = ['PM2.5',	'PM10',	'SO2',	'NO2',	'CO',	'O3',	'TEMP',	'PRES',	'DEWP',	'RAIN',	'WSPM']
for_loop_forecast1=pd.DataFrame()

for weeks in ticker_list:
  # Get the data for the ticker
  group1 = groups_by_ticker.get_group(weeks)  
  # Make forecast
  forecast1 = train_and_forecast(group1)
  # Add the forecast results to the dataframe
  #for_loop_forecast1 = pd.concat((for_loop_forecast1, forecast1))

INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/8mch8nm_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/o3k3iz26.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.9/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=73139', 'data', 'file=/tmp/tmp0lbuvohe/8mch8nm_.json', 'init=/tmp/tmp0lbuvohe/o3k3iz26.json', 'output', 'file=/tmp/tmp0lbuvohe/prophet_modele2icpvz6/prophet_model-20230321173543.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
17:35:43 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
17:36:01 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/g1bskm7d.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/7vcur6j4.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.9/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=24921', 'data', 'file=/tmp/tmp0lbuvohe/g1bskm7d.json', 'init=/tmp/tmp0lbuvohe/7vcur6j4.json', 'output', 'file=/tmp/tmp0lbuvohe/prophet_modelj6buh46p/prophet_model-20230321173619.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
17:36:19 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
17:36:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/r8v9hzmq.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/8xhi959b.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.9/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=88298', 'data', 'file=/tmp/tmp0lbuvohe/r8v9hzmq.json', 'init=/tmp/tmp0lbuvohe/8xhi959b.json', 'output', 'file=/tmp/tmp0lbuvohe/prophet_modelwdfsqdzr/prophet_model-20230321173651.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
17:36:51 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
17:37:12 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/fclk4b8_.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/u4fb6c8r.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.9/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=87346', 'data', 'file=/tmp/tmp0lbuvohe/fclk4b8_.json', 'init=/tmp/tmp0lbuvohe/u4fb6c8r.json', 'output', 'file=/tmp/tmp0lbuvohe/prophet_model1wo5qpld/prophet_model-20230321173724.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
17:37:24 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
17:37:39 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/1zr2mq7b.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/52c4qw46.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.9/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=65144', 'data', 'file=/tmp/tmp0lbuvohe/1zr2mq7b.json', 'init=/tmp/tmp0lbuvohe/52c4qw46.json', 'output', 'file=/tmp/tmp0lbuvohe/prophet_modelvp6noext/prophet_model-20230321173752.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
17:37:52 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
17:38:20 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/tbxijahd.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/od1c3o3p.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.9/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=99778', 'data', 'file=/tmp/tmp0lbuvohe/tbxijahd.json', 'init=/tmp/tmp0lbuvohe/od1c3o3p.json', 'output', 'file=/tmp/tmp0lbuvohe/prophet_model8n6890d8/prophet_model-20230321173832.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
17:38:32 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
17:38:54 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/htaby_mz.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/_39gqocf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.9/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=8882', 'data', 'file=/tmp/tmp0lbuvohe/htaby_mz.json', 'init=/tmp/tmp0lbuvohe/_39gqocf.json', 'output', 'file=/tmp/tmp0lbuvohe/prophet_modelh4loiip9/prophet_model-20230321173906.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
17:39:06 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
17:39:26 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/pjw90m7y.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/kka2zxmd.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.9/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=22147', 'data', 'file=/tmp/tmp0lbuvohe/pjw90m7y.json', 'init=/tmp/tmp0lbuvohe/kka2zxmd.json', 'output', 'file=/tmp/tmp0lbuvohe/prophet_modeljusnrzq4/prophet_model-20230321173938.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
17:39:38 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
17:40:05 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/_jv2yu_a.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/izv9co_5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.9/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55719', 'data', 'file=/tmp/tmp0lbuvohe/_jv2yu_a.json', 'init=/tmp/tmp0lbuvohe/izv9co_5.json', 'output', 'file=/tmp/tmp0lbuvohe/prophet_modelvr4hd0b4/prophet_model-20230321174017.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
17:40:17 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
17:40:41 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/08gstxwl.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/yni_kkx5.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.9/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=55463', 'data', 'file=/tmp/tmp0lbuvohe/08gstxwl.json', 'init=/tmp/tmp0lbuvohe/yni_kkx5.json', 'output', 'file=/tmp/tmp0lbuvohe/prophet_model6pi6iuyl/prophet_model-20230321174053.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
17:40:53 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
17:41:02 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing
INFO:prophet:Disabling yearly seasonality. Run prophet with yearly_seasonality=True to override this.
INFO:prophet:Disabling weekly seasonality. Run prophet with weekly_seasonality=True to override this.
INFO:prophet:Disabling daily seasonality. Run prophet with daily_seasonality=True to override this.
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/y_fygd8o.json
DEBUG:cmdstanpy:input tempfile: /tmp/tmp0lbuvohe/0pv6n_vf.json
DEBUG:cmdstanpy:idx 0
DEBUG:cmdstanpy:running CmdStan, num_threads: None
DEBUG:cmdstanpy:CmdStan args: ['/usr/local/lib/python3.9/dist-packages/prophet/stan_model/prophet_model.bin', 'random', 'seed=23604', 'data', 'file=/tmp/tmp0lbuvohe/y_fygd8o.json', 'init=/tmp/tmp0lbuvohe/0pv6n_vf.json', 'output', 'file=/tmp/tmp0lbuvohe/prophet_modelyikqgl39/prophet_model-20230321174114.csv', 'method=optimize', 'algorithm=lbfgs', 'iter=10000']
17:41:14 - cmdstanpy - INFO - Chain [1] start processing
INFO:cmdstanpy:Chain [1] start processing
17:41:31 - cmdstanpy - INFO - Chain [1] done processing
INFO:cmdstanpy:Chain [1] done processing

In [ ]:
for_loop_forecast1.head()

                             ds  weeks        yhat  yhat_lower  yhat_upper
0 1970-01-01 00:00:00.000000000  PM2.5  102.243586   -1.366127  200.814825
1 1970-01-01 00:00:00.000000001  PM2.5  102.229464    0.696170  198.712883
2 1970-01-01 00:00:00.000000002  PM2.5  102.215341    1.366024  202.140183
3 1970-01-01 00:00:00.000000003  PM2.5  102.201219    5.481432  201.351866
4 1970-01-01 00:00:00.000000004  PM2.5  102.187096   -6.084310  205.459062

In [ ]:
forecast1.head()

                             ds weeks      yhat  yhat_lower  yhat_upper
0 1970-01-01 00:00:00.000000000  WSPM  2.241994    0.727636    3.671046
1 1970-01-01 00:00:00.000000001  WSPM  2.241695    0.812380    3.692658
2 1970-01-01 00:00:00.000000002  WSPM  2.241397    0.743464    3.621831
3 1970-01-01 00:00:00.000000003  WSPM  2.241099    0.784705    3.805163
4 1970-01-01 00:00:00.000000004  WSPM  2.240800    0.693973    3.686955

In [ ]:
yhat=forecast1['yhat']
yhat.head()

0    2.241994
1    2.241695
2    2.241397
3    2.241099
4    2.240800
Name: yhat, dtype: float64

In [ ]:
y=df['y']
y.head()

0    4.0
1    8.0
2    7.0
3    6.0
4    3.0
Name: y, dtype: float64

In [ ]:
from sklearn.metrics import mean_absolute_percentage_error as mape
print('mape : ', mape(y[:35064],yhat[:35089]))

mape :  0.9353064048453115